project:
  type: website
  resources:
    - letitrip/*
    - humansim/*

website:
  title: "Oh Cluck!"
  favicon: assets/H5N10001.png
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - text: Simulations
        menu:
        - href: https://kortessis-lab.shinyapps.io/h5n1/
          text: Dairy Outbreak Simulation
        - href: https://medewitt.github.io/poultry-farm-game/
          text: Poultry Farm Game
        - href: letitrip/index.html
          text: Let It Rip
        - href: humansim/index.html
          text: Human spillover
      - virology.qmd
      - vaccines.qmd
      - text: Epidemiology
        menu:
        - href: https://www.google.com/maps/d/u/0/viewer?mid=1WMtzvlPqvv2o4PQEitCgoxtxlSjfqcw&ll=34.126511881565904%2C-63.77444320884649&z=4
          text: Outbreak Map
        - href: https://cafomaps.org/by-state/nc.html
          text: Concentrated Animal Feeding Operations in NC
      - about.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    css: assets/styles.css
    toc: true
    include-in-header: fragments/header.html
    include-after-body: fragments/footer.html
    bibliography: references.bib

